[packages.common]
all = [
    "7zip",
    "bat",
    "bottom",
    "chezmoi",
    "difftastic",
    "discord",
    "dotnet-sdk",
    "dust",
    "eza",
    "fastfetch",
    "fclones",
    "fd",
    "ffmpeg",
    "fzf",
    "gcc",
    "git",
    "gitui",
    "hyperfine",
    "jq",
    "keepassxc",
    "lazygit",
    "less",
    "lua51",
    "luarocks",
    "lz4",
    "mediainfo",
    "mpv",
    "neovim",
    "ouch",
    "pueue",
    "python",
    "ripgrep",
    "starship",
    "tldr",
    "typst",
    "yazi",
    "yt-dlp",
    "zig",
    "zoxide",
]
linux = [
    "aur/fend-bin",
    "aur/zen-browser-bin",
    "git-delta",
    "jujutsu",
    "npm",
    "nushell",
    "proton-vpn-gtk-app",
    "ripgrep-all",
    "rustup",
    "rust-analyzer",
    "ttf-hack-nerd",
]
windows = [
    "Hack-NF-Mono",
    "delta",
    "fend",
    "jj",
    "nodejs",
    "nu",
    "protonvpn-np",
    "rga",
    "rustup-gnu",
    "zen-browser",
]

[packages]
linux = [
    "atuin",
    "ghostty",
    "make",
    "man-db",
    "noto-fonts", # ttf-font provider
    "openssh",
    "pipewire-jack", # jack provider
    "python-virtualenv",
    "rsync",
    "skim",
    "unzip",
    "wget",
    "xsel",
    "zellij",
]
windows = [
    "aria2",
    "glazewm-np",
    "gzip", # mason fails to install tree-sitter-cli without
    "powertoys",
    "wezterm",
    "zebar",
]
