[lazyvim]
extras = [
    "coding.mini-surround",
    "coding.neogen",
    "coding.yanky",
    "dap.core",
    "dap.nlua",
    "editor.aerial",
    "editor.dial",
    "editor.inc-rename",
    "lang.clangd",
    "lang.cmake",
    "lang.docker",
    "lang.dotnet",
    "lang.git",
    "lang.json",
    "lang.markdown",
    "lang.nushell",
    "lang.python",
    "lang.rust",
    "lang.toml",
    "lang.yaml",
    "lang.zig",
    "test.core",
    "ui.treesitter-context",
    "util.chezmoi",
    "util.dot",
    "util.mini-hipatterns",
]
install_version = 8
